import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import localFont from "next/font/local";
import LenisProvider from "@/components/LenisProvider";
import "lenis/dist/lenis.css";
import "./globals.css";
import { cn } from "@/lib/utils";

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const specialGothic = localFont({
  src: "./fonts/special-gothic-ttf/SpecialGothic-Medium.ttf",
  variable: "--font-special-gothic",
  weight: "500",
});

const specialExpanded = localFont({
  src: "./fonts/special-gothic-ttf/SpecialGothicExpanded-Bold.ttf",
  variable: "--font-special-expanded",
  weight: "700",
});

const rocGrotesk = localFont({
  src: [
    {
      path: "./fonts/roc-grotesk-woff2/Roc Grotesk Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/roc-grotesk-woff2/Roc Grotesk Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/roc-grotesk-woff2/Roc Grotesk Thin.woff2",
      weight: "100",
      style: "normal",
    },
  ],
  variable: "--font-roc-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, specialGothic.variable, specialExpanded.variable, rocGrotesk.variable, "font-mono", jetbrainsMono.variable)}
    >
      <body className="min-h-full flex flex-col">
        <LenisProvider>
          {children}
        </LenisProvider>
      </body>
    </html>
  );
}
