import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const specialGothic = localFont({
  src: "./fonts/special-gothic-ttf/SpecialGothic-Medium.ttf",
  variable: "--font-special-gothic",
  weight: "500",
});

const specialExpanded = localFont({
  src: "./fonts/special-gothic-ttf/SpecialGothicExpanded-Bold.ttf",
  variable: "--font-special-expanded",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${specialGothic.variable} ${specialExpanded.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
